### ISSUE TITLE
Initial implementation (1.0.0a1)

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-logos-block#1]
# ToDo

- [x] create "Logos Block" (copy of Grid Block)
- [x] allow adding "Logo" subblocks
- [x] allow adding a title to a "Logo" subblock
- [ ] when choosing an existing image the title of the image will be copied over to the "Logo" subblock
- [x] allow adding a link to a logo
- [ ] take into account that we will add an option "grey out logos on hover" at a later point (in case we have to prepare anything)

# Visual Design

We implement the "Logos only" version only for now:

![Logo-Block_ Colored](https://github.com/kitconcept/volto-logos-block/assets/632105/d97a50fd-0d50-4ae4-a1be-3230437aaa0f)

Greyed out on hover version (later):

![Logo-Block_ Black   White](https://github.com/kitconcept/volto-logos-block/assets/632105/a462055e-543c-4293-a5e1-4612a8ff82bd)

**Comment by tisto** [comment]
@jackahl the criteria for the initial implementation are not met yet:

- when choosing an existing image the title of the image will be copied over to the "Logo" subblock -> this doesn't work
- we show a description field, which wasn't specified. if we keep it it should be a multi-line field
- the image label has a description "It is advised to use a svg graphic." -> this is not correct AFAIK, we only support SVG graphics, isn't that correct?
